### PR TITLE
feat: add timezone to dockerfile, expected to sync erddap and buoy api

### LINKED ISSUE #39: Set time zone in Dockerfile
Add this command to dockerfile

```
sudo timedatectl set-timezone America/New_York
```

you may need some `yum install` to get `timedatectl`

### PR DESCRIPTION
**Pull request by tdivoll**
The added commands should add the correct timezone and be robust to deployment as well as CI actions. 

https://serverfault.com/questions/683605/docker-container-time-timezone-will-not-reflect-changes

Closes #39

### CODE REVIEW

**Review by kmilo9999 — APPROVED** [review]
looks good to me

**Comment by tdivoll** [comment]
closes #39

**Review by mirestrepo — APPROVED** [review]
Looks good to me, although I would wait to merge #40 so when you merge `main` into this a new container is built and you can check that the timezone is working as expected

**Comment by tdivoll** [comment]
This is curious, the build time in the CI is in the future. At time of writing this, it is 12-2-2022 @ 19:33 (7:33 pm). 
image

**Comment by mirestrepo** [comment]
That’s probably okay. That’s the time or the GitHub runner which is likely UTC. That’s not related to the time inside of of the container. Happy to show you how to test that on Monday if you’re not familiar with that. On Dec 2, 2022, at 7:34 PM, Timothy Divoll ***@***.***> wrote:﻿
This is curious, the build time in the CI is in the future. At time of writing this, it is 12-2-2022 @ 19:33 (7:33 pm).

**Comment by tdivoll** [comment]
@mirestrepo That would be great! The docker build seemed to be five hours in the future, which makes sense now, I was expecting 4 hours, but forgot about daylight savings time 🤭

**Pull request merged**
